-- 001_core_schema.sql
-- Core tables for niche scoring pipeline (Algo Spec V1.1)

-- Reports generated by the scoring engine (M9 output)
CREATE TABLE IF NOT EXISTS reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    spec_version TEXT NOT NULL DEFAULT '1.1',
    niche_keyword TEXT NOT NULL,
    geo_scope TEXT NOT NULL,
    geo_target TEXT NOT NULL,
    report_depth TEXT NOT NULL DEFAULT 'standard',
    strategy_profile TEXT NOT NULL DEFAULT 'balanced',
    resolved_weights JSONB,
    keyword_expansion JSONB,
    metros JSONB,
    meta JSONB,
    feedback_log_id UUID
);

CREATE INDEX idx_reports_niche ON reports (niche_keyword);
CREATE INDEX idx_reports_created ON reports (created_at DESC);

-- Expanded keywords per report
CREATE TABLE IF NOT EXISTS report_keywords (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id UUID NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    keyword TEXT NOT NULL,
    tier INT NOT NULL CHECK (tier IN (1, 2, 3)),
    intent TEXT NOT NULL CHECK (intent IN ('transactional', 'commercial', 'informational')),
    source TEXT NOT NULL,
    aio_risk TEXT NOT NULL DEFAULT 'low',
    search_volume INT,
    cpc NUMERIC
);

CREATE INDEX idx_report_keywords_report ON report_keywords (report_id);

-- Extracted signals per metro per report
CREATE TABLE IF NOT EXISTS metro_signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id UUID NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    cbsa_code TEXT NOT NULL,
    cbsa_name TEXT NOT NULL,
    demand JSONB,
    organic_competition JSONB,
    local_competition JSONB,
    ai_resilience JSONB,
    monetization JSONB
);

CREATE INDEX idx_metro_signals_report ON metro_signals (report_id);

-- Computed scores per metro per report
CREATE TABLE IF NOT EXISTS metro_scores (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id UUID NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    cbsa_code TEXT NOT NULL,
    demand_score INT,
    organic_competition_score INT,
    local_competition_score INT,
    monetization_score INT,
    ai_resilience_score INT,
    opportunity_score INT,
    confidence_score INT,
    confidence_flags JSONB,
    serp_archetype TEXT,
    ai_exposure TEXT,
    difficulty_tier TEXT,
    guidance JSONB
);

CREATE INDEX idx_metro_scores_report ON metro_scores (report_id);
CREATE INDEX idx_metro_scores_opportunity ON metro_scores (opportunity_score DESC);

-- Feedback log for future bandit optimisation (Algo Spec V1.1, §9)
CREATE TABLE IF NOT EXISTS feedback_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    context JSONB NOT NULL,
    signals JSONB NOT NULL,
    scores JSONB NOT NULL,
    classification JSONB NOT NULL,
    recommendation_rank INT,
    outcome JSONB
);

CREATE INDEX idx_feedback_log_niche ON feedback_log ((context->>'niche_keyword'));
